# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
          # cmd: npm run build

      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: install #yarn insatll or npm install

      - name: creating build
        run: yarn build
        # run: npm run build
      
      - name: Install Surge
        run: npm install --global surge
      
      - name: Deploying Project on Surge
        run: surge ./1-Reactjs/build http://reactjs-hkbenvision.surge.sh --token  "b49fbf275d0a9c03b3efddfd73264fb7"
           